# Generated by Django 5.2 on 2026-02-12 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='drink',
            name='is_special',
            field=models.BooleanField(default=False),
        ),
    ]
