# Generated by Django 5.2 on 2026-02-12 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0002_drink_is_special'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('image', models.ImageField(upload_to='menu/')),
                ('category', models.CharField(choices=[('DRINK', 'Drink'), ('SNACK', 'Snack')], default='DRINK', max_length=10)),
                ('season', models.CharField(choices=[('ALL', 'All Year'), ('SUMMER', 'Summer Coolers'), ('MONSOON', 'Monsoon Snacks'), ('WINTER', 'Winter Warmers')], default='ALL', max_length=10)),
                ('is_special', models.BooleanField(default=False)),
                ('is_seasonal', models.BooleanField(default=False)),
            ],
        ),
        migrations.DeleteModel(
            name='Drink',
        ),
    ]
