# Generated by Django 5.2 on 2026-02-12 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0003_menuitem_delete_drink'),
    ]

    operations = [
        migrations.CreateModel(
            name='FranchisePackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location_type', models.CharField(choices=[('MALL', 'Mall'), ('COLLEGE', 'College'), ('BEACH', 'Beach'), ('HIGHWAY', 'Highway')], max_length=10)),
                ('investment_range', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('setup_time', models.CharField(default='4-6 weeks', max_length=50)),
                ('image', models.ImageField(upload_to='franchise/')),
            ],
        ),
    ]
