# Generated by Django 5.2 on 2026-02-12 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0004_franchisepackage'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='temp_type',
            field=models.CharField(choices=[('HOT', 'Hot'), ('COLD', 'Cold'), ('NA', 'N/A')], default='COLD', max_length=5),
        ),
    ]
