# Generated by Django 5.2 on 2026-02-12 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0005_menuitem_temp_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='category',
            field=models.CharField(choices=[('DRINK', 'Drink'), ('SMOOTHIE', 'Smoothie'), ('SNACK', 'Snack')], default='DRINK', max_length=10),
        ),
    ]
