# Generated by Django 5.2 on 2026-02-12 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0007_menuitem_is_gluten_free_menuitem_is_vegan_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='menu_section',
            field=models.CharField(choices=[('SHAWARMA_ROLL', 'Chicken Shawarma Roll'), ('SHAWARMA_PLATE', 'Chicken Shawarma Plate'), ('GRILLED_CHICKEN', 'Grilled Chicken'), ('BBQ_CHICKEN', 'Barbeque Chicken'), ('TANDOORI_CHICKEN', 'Tandoori Chicken'), ('VEG_STARTERS', 'Veg Starters'), ('OTHER', 'Other')], default='OTHER', max_length=20),
        ),
    ]
