# Generated by Django 5.2 on 2026-02-13 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0008_menuitem_menu_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='category',
            field=models.CharField(choices=[('DRINK', 'Drink'), ('SMOOTHIE', 'Smoothie'), ('SNACK', 'Snack'), ('STARTER', 'Indian Starter'), ('COMBO', 'Combo')], default='DRINK', max_length=10),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='menu_section',
            field=models.CharField(choices=[('SHAWARMA_ROLL', 'Chicken Shawarma Roll'), ('SHAWARMA_PLATE', 'Chicken Shawarma Plate'), ('GRILLED_CHICKEN', 'Grilled Chicken'), ('BBQ_CHICKEN', 'Barbeque Chicken'), ('TANDOORI_CHICKEN', 'Tandoori Chicken'), ('VEG_STARTERS', 'Veg Starters'), ('LOADED_FRIES', 'Loaded Fries'), ('FUSION_CHAAT', 'Fusion Chaat'), ('FAMILY_BOX', 'Family Box'), ('PARTY_PACK', 'Party Pack'), ('OTHER', 'Other')], default='OTHER', max_length=20),
        ),
    ]
